export const galleryTourSteps = [
  {
    target: 'body',
    placement: 'center',
    icon: "🖼",
    title: 'Welcome to the Gallery',
    content: "Browse real event setups and get inspired. Filter by type, year, venue style, and save your favorites for later.",
  },
  {
    target: '.events-quick-links',
    placement: 'auto',
    icon: "⚡",
    title: 'Quick Access',
    content: 'Jump directly to specific event types like weddings, corporate events, or view all events at once.',
  },
  {
    target: '.events-bookmark-shortcut',
    placement: 'auto',
    icon: "🔖",
    title: 'Your Saved Events',
    content: 'Quick access to all your bookmarked events. The number shows how many you have saved.',
  },
  {
    target: '.events-sidebar',
    placement: 'auto',
    icon: "🔍",
    title: 'Smart Filters',
    content: 'Refine your search using these filters. Search by text, event type, year, and venue style to find exactly what you need.',
  },
  {
    target: '.events-search-box',
    placement: 'auto',
    icon: "🔎",
    title: 'Search',
    content: 'Search for events by name, venue, or setup style. Try keywords like wedding, lawn, home, or rooftop.',
  },
  {
    target: '.events-filter-group',
    placement: 'auto',
    icon: "🏷",
    title: 'Filter Groups',
    content: 'Check the boxes to filter by event type, year, or venue style. Combine multiple filters for precise results.',
  },
  {
    target: '.events-sort-box',
    placement: 'auto',
    icon: "↕",
    title: 'Sort Options',
    content: 'Sort events by date (latest or oldest) or by budget (highest or lowest) to find what matches your needs.',
  },
  {
    target: '.events-grid',
    placement: 'auto',
    icon: "📋",
    title: 'Event Cards',
    content: 'Each card shows an event setup. Click to view details in a modal, or use the bookmark icon to save for later.',
  },
];
